### ISSUE TITLE
Wiki access broken

### ISSUE THREAD

**Issue by jhnstrk** [ianepperson/pyredminews#35]
Accessing a wiki page results in:

<pre>
>>> w = project.wiki_pages.get('Sandbox')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27x64\lib\site-packages\pyredmine-0.2.4-py2.7.egg\redmine\redmine_rest.py", line 542, in get
    target = self._item_path % id
TypeError: unsupported operand type(s) for %: 'tuple' and 'str'
</pre>

I have the master version at commit 34f43e2d94b156f8ed0588e7cfbcf1d74d852af0 , accessing a redmine 2.3 server. 

There seems to be a trailing comma at line 542 of redmine.py.

The patch is simple:

<pre>
diff --git a/redmine/redmine.py b/redmine/redmine.py
index a589935..648ecfa 100644
--- a/redmine/redmine.py
+++ b/redmine/redmine.py
@@ -539,7 +539,7 @@ class Redmine_Wiki_Pages_Manager(Redmine_Items_Manager):

     def __init__(self, redmine, project):
         # Call the base class constructor
-        path = '/projects/%s/wiki/%%s.json' % project.id,
+        path = '/projects/%s/wiki/%%s.json' % project.id
         Redmine_Items_Manager.__init__(self, redmine, Wiki_Page,
                                        item_path=path,
                                        item_new_path=path)
</pre>

**Comment by jhnstrk** [comment]
The patch fixed the bug for me.
