### ISSUE TITLE
AttributeError: 'Issue' object has no attribute 'journals'

### ISSUE THREAD

**Issue by sieppl** [ianepperson/pyredminews#41]
Hi, 

my environment:
- Windows 8.1
- Python 2.7 (just installed)
- latest pyredmine (installed via powershell script)

```
Traceback (most recent call last):
  File "redmine_issues_to_bitbucket.py", line 295, in <module>
    feed.addIssue(issue)
  File "redmine_issues_to_bitbucket.py", line 193, in addIssue
    for journal in redmineIssue.journals:
AttributeError: 'Issue' object has no attribute 'journals'
```

**Comment by khelll** [comment]
Same problem here

**Comment by deathwishdave** [comment]
+1

**Comment by deathwishdave** [comment]
I have bypassed the error by downgrading to 93ab20323d68e5af4ded7d5d2f5623250cdabe00
