### ISSUE TITLE
PyPI package install not working.

### ISSUE THREAD

**Issue by ianepperson** [ianepperson/pyredminews#9]
Late tonight and I'm missing something.  Need to chase it when I'm fresh.

Any suggestions as to what I've done wrong are welcome.

**Comment by ianepperson** [comment]
On Windows:

Y:\Dropbox\Code>pip install pyredmine
Downloading/unpacking pyredmine
  Running setup.py egg_info for package pyredmine
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "c:\docume~1\ian\locals~1\temp\pip-build\pyredmine\setup.py", line 14
, in <module>
        long_description = readme(),
      File "c:\docume~1\ian\locals~1\temp\pip-build\pyredmine\setup.py", line 4,
 in readme
        with open('README.rst') as f:
    IOError: [Errno 2] No such file or directory: 'README.rst'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "c:\docume~1\ian\locals~1\temp\pip-build\pyredmine\setup.py", line 14, in
 <module>

```
long_description = readme(),
```

  File "c:\docume~1\ian\locals~1\temp\pip-build\pyredmine\setup.py", line 4, in
readme

```
with open('README.rst') as f:
```

IOError: [Errno 2] No such file or directory: 'README.rst'

---

Command python setup.py egg_info failed with error code 1 in c:\docume~1\ian\loc
als~1\temp\pip-build\pyredmine
Storing complete log in C:\Documents and Settings\Ian\pip\pip.log

**Comment by ianepperson** [comment]
Also need to add dateutil to requirements.

**Comment by sasvari** [comment]
Not sure if this is the same problem, but for me the pypi package is not working as well.

While trying to get the user list from within ipython, there's an 404 error:

```
HTTPError: HTTP Error 404: Not Found
```

Problem:
There is something wrong with how pyredminews assembles the URL for the GET process, this occurs in my redmine log:

```
ActionController::RoutingError (No route matches "//users.json" with {:method=>:get}):
```

Obviously it puts an additional `/` to the URL and tries to access `http://server/redmine//users.json` instead of `http://server/redmine/users.json`.

**Comment by ianepperson** [comment]
Thanks for the report Sasvari, but it isn't the same problem - please open a new bug for that.  Be sure and note the version of Redmine you're using; if you're using 1.0, then the "users" are not available.  I've been testing against 1.1 and 2.2 and neither this old nor new version complained to me about the double slashes in the URL.  It's not difficult to remove them.
